use super::{CommandOption, CommandSpec};

pub fn builtin_command_specs() -> Vec<CommandSpec> {
    let mut specs = vec![
        git(),
        docker(),
        docker_compose(),
        cargo(),
        rustup(),
        package_manager("npm", "Node package manager"),
        package_manager("pnpm", "Fast, disk-efficient package manager"),
        package_manager("yarn", "JavaScript package manager"),
        package_manager("bun", "JavaScript runtime and toolkit"),
        kubectl(),
        gh(),
        brew(),
        go(),
        helm(),
        terraform(),
        podman(),
        python_tool("pip", "Python package installer"),
        python_tool("pip3", "Python 3 package installer"),
        python_tool("uv", "Fast Python package manager"),
        simple(
            "just",
            "Command runner",
            &[
                "choose", "dump", "edit", "evaluate", "groups", "list", "show", "summary",
            ],
        ),
        simple(
            "make",
            "Build automation tool",
            &["all", "build", "clean", "install", "test"],
        ),
        simple(
            "systemctl",
            "System service manager",
            &[
                "cat",
                "daemon-reload",
                "disable",
                "enable",
                "is-active",
                "list-units",
                "reload",
                "restart",
                "start",
                "status",
                "stop",
            ],
        ),
    ];
    specs.extend(additional_tools());
    specs
}

fn git() -> CommandSpec {
    let mut commit = leaf("commit", "Record changes to the repository");
    commit.options = options(&[
        ("-a", "Stage tracked changes"),
        ("-m", "Use the given commit message"),
        ("--amend", "Replace the tip commit"),
        ("--no-verify", "Bypass commit hooks"),
        ("--signoff", "Add a Signed-off-by trailer"),
    ]);
    let mut root = node(
        "git",
        "Distributed version control",
        vec![
            leaf("add", "Add file contents to the index"),
            leaf("bisect", "Find a change by binary search"),
            leaf("branch", "List, create, or delete branches"),
            leaf("checkout", "Switch branches or restore files"),
            leaf("cherry-pick", "Apply existing commits"),
            leaf("clone", "Clone a repository"),
            commit,
            leaf("diff", "Show changes between revisions"),
            leaf("fetch", "Download objects and refs"),
            leaf("init", "Create an empty repository"),
            leaf("log", "Show commit history"),
            leaf("merge", "Join development histories"),
            leaf("pull", "Fetch and integrate changes"),
            leaf("push", "Update remote refs"),
            leaf("rebase", "Reapply commits on another base"),
            node(
                "remote",
                "Manage remotes",
                leaves(&[
                    "add", "get-url", "prune", "remove", "rename", "set-head", "set-url", "show",
                    "update",
                ]),
            ),
            leaf("reset", "Reset the current HEAD"),
            leaf("restore", "Restore working tree files"),
            leaf("revert", "Create commits that reverse changes"),
            leaf("show", "Show objects"),
            node(
                "stash",
                "Stash working tree changes",
                leaves(&[
                    "apply", "branch", "clear", "create", "drop", "list", "pop", "push", "show",
                    "store",
                ]),
            ),
            leaf("status", "Show the working tree status"),
            leaf("switch", "Switch branches"),
            leaf("tag", "Create, list, or delete tags"),
            node(
                "worktree",
                "Manage linked working trees",
                leaves(&[
                    "add", "list", "lock", "move", "prune", "remove", "repair", "unlock",
                ]),
            ),
        ],
    );
    root.options = options(&[
        ("-C", "Run as if started in a directory"),
        ("-c", "Set a configuration value"),
        ("--version", "Show version information"),
        ("--help", "Show help"),
    ]);
    root
}

fn docker() -> CommandSpec {
    let compose = compose_spec();
    node(
        "docker",
        "Build, run, and manage containers",
        vec![
            leaf("build", "Build an image from a Dockerfile"),
            compose,
            node(
                "container",
                "Manage containers",
                leaves(&[
                    "attach", "commit", "cp", "create", "diff", "exec", "export", "inspect",
                    "kill", "logs", "ls", "pause", "port", "prune", "rename", "restart", "rm",
                    "run", "start", "stats", "stop", "top", "unpause", "update", "wait",
                ]),
            ),
            node(
                "context",
                "Manage Docker contexts",
                leaves(&[
                    "create", "export", "import", "inspect", "ls", "rm", "show", "update", "use",
                ]),
            ),
            leaf("exec", "Run a command in a running container"),
            node(
                "image",
                "Manage images",
                leaves(&[
                    "build", "history", "import", "inspect", "load", "ls", "prune", "pull", "push",
                    "rm", "save", "tag",
                ]),
            ),
            leaf("images", "List images"),
            leaf("info", "Display system information"),
            leaf("inspect", "Return low-level object information"),
            leaf("login", "Authenticate to a registry"),
            leaf("logout", "Log out from a registry"),
            leaf("logs", "Fetch container logs"),
            node(
                "network",
                "Manage networks",
                leaves(&[
                    "connect",
                    "create",
                    "disconnect",
                    "inspect",
                    "ls",
                    "prune",
                    "rm",
                ]),
            ),
            leaf("ps", "List containers"),
            leaf("pull", "Download an image"),
            leaf("push", "Upload an image"),
            leaf("run", "Run a command in a new container"),
            leaf("start", "Start stopped containers"),
            leaf("stats", "Display resource usage"),
            leaf("stop", "Stop running containers"),
            node(
                "system",
                "Manage Docker",
                leaves(&["df", "events", "info", "prune"]),
            ),
            leaf("version", "Show Docker version"),
            node(
                "volume",
                "Manage volumes",
                leaves(&["create", "inspect", "ls", "prune", "rm"]),
            ),
        ],
    )
}

fn compose_spec() -> CommandSpec {
    node(
        "compose",
        "Define and run multi-container applications",
        vec![
            leaf("build", "Build or rebuild services"),
            leaf("config", "Parse and validate the Compose file"),
            leaf("create", "Create services"),
            leaf("down", "Stop and remove services"),
            leaf("events", "Receive real-time container events"),
            leaf("exec", "Run a command in a running service"),
            leaf("images", "List images used by containers"),
            leaf("kill", "Force stop service containers"),
            leaf("logs", "View output from containers"),
            leaf("ls", "List Compose projects"),
            leaf("pause", "Pause services"),
            leaf("port", "Print a public port binding"),
            leaf("ps", "List service containers"),
            leaf("pull", "Pull service images"),
            leaf("push", "Push service images"),
            leaf("restart", "Restart service containers"),
            leaf("rm", "Remove stopped service containers"),
            leaf("run", "Run a one-off command"),
            leaf("start", "Start services"),
            leaf("stop", "Stop services"),
            leaf("top", "Display running processes"),
            leaf("unpause", "Unpause services"),
            leaf("up", "Create and start services"),
            leaf("version", "Show Compose version"),
            leaf("wait", "Wait for containers to stop"),
            leaf("watch", "Watch build context and rebuild"),
        ],
    )
}

fn docker_compose() -> CommandSpec {
    let mut compose = compose_spec();
    compose.name = "docker-compose".into();
    compose.description = Some("Define and run multi-container applications".into());
    compose
}

fn cargo() -> CommandSpec {
    let mut root = simple(
        "cargo",
        "Rust package manager",
        &[
            "add",
            "bench",
            "build",
            "check",
            "clean",
            "clippy",
            "doc",
            "fetch",
            "fix",
            "generate-lockfile",
            "help",
            "init",
            "install",
            "locate-project",
            "login",
            "metadata",
            "new",
            "owner",
            "package",
            "publish",
            "remove",
            "report",
            "run",
            "rustc",
            "rustdoc",
            "search",
            "test",
            "tree",
            "uninstall",
            "update",
            "vendor",
            "verify-project",
            "version",
            "yank",
        ],
    );
    root.options = options(&[
        ("--locked", "Require Cargo.lock to be unchanged"),
        ("--offline", "Run without network access"),
        ("--frozen", "Require lockfile and cache to be unchanged"),
    ]);
    root
}

fn rustup() -> CommandSpec {
    simple(
        "rustup",
        "Rust toolchain installer",
        &[
            "check",
            "component",
            "completions",
            "default",
            "doc",
            "help",
            "man",
            "override",
            "profile",
            "run",
            "self",
            "set",
            "show",
            "target",
            "toolchain",
            "update",
            "which",
        ],
    )
}

fn package_manager(name: &str, description: &str) -> CommandSpec {
    simple(
        name,
        description,
        &[
            "add",
            "audit",
            "bin",
            "cache",
            "config",
            "create",
            "dedupe",
            "exec",
            "help",
            "init",
            "install",
            "link",
            "list",
            "login",
            "logout",
            "outdated",
            "pack",
            "prune",
            "publish",
            "rebuild",
            "remove",
            "run",
            "search",
            "start",
            "test",
            "uninstall",
            "update",
            "version",
            "why",
        ],
    )
}

fn kubectl() -> CommandSpec {
    let mut root = simple(
        "kubectl",
        "Kubernetes command-line tool",
        &[
            "alpha",
            "annotate",
            "api-resources",
            "api-versions",
            "apply",
            "attach",
            "auth",
            "autoscale",
            "certificate",
            "cluster-info",
            "completion",
            "config",
            "cordon",
            "cp",
            "create",
            "debug",
            "delete",
            "describe",
            "diff",
            "drain",
            "edit",
            "events",
            "exec",
            "explain",
            "expose",
            "get",
            "kustomize",
            "label",
            "logs",
            "options",
            "patch",
            "plugin",
            "port-forward",
            "proxy",
            "replace",
            "rollout",
            "run",
            "scale",
            "set",
            "taint",
            "top",
            "uncordon",
            "version",
            "wait",
        ],
    );
    root.aliases.push("k".into());
    root
}

fn gh() -> CommandSpec {
    simple(
        "gh",
        "GitHub command-line interface",
        &[
            "alias",
            "api",
            "auth",
            "browse",
            "cache",
            "codespace",
            "completion",
            "config",
            "extension",
            "gist",
            "gpg-key",
            "issue",
            "label",
            "org",
            "pr",
            "project",
            "release",
            "repo",
            "ruleset",
            "run",
            "search",
            "secret",
            "ssh-key",
            "status",
            "variable",
            "workflow",
        ],
    )
}

fn brew() -> CommandSpec {
    simple(
        "brew",
        "Homebrew package manager",
        &[
            "analytics",
            "autoremove",
            "bundle",
            "cleanup",
            "commands",
            "config",
            "deps",
            "doctor",
            "fetch",
            "formulae",
            "home",
            "info",
            "install",
            "leaves",
            "link",
            "list",
            "livecheck",
            "outdated",
            "pin",
            "reinstall",
            "search",
            "services",
            "shellenv",
            "tap",
            "uninstall",
            "unlink",
            "unpin",
            "untap",
            "update",
            "upgrade",
            "uses",
        ],
    )
}

fn go() -> CommandSpec {
    simple(
        "go",
        "Go toolchain",
        &[
            "bug",
            "build",
            "clean",
            "doc",
            "env",
            "fix",
            "fmt",
            "generate",
            "get",
            "install",
            "list",
            "mod",
            "run",
            "telemetry",
            "test",
            "tool",
            "version",
            "vet",
            "work",
        ],
    )
}

fn helm() -> CommandSpec {
    simple(
        "helm",
        "Kubernetes package manager",
        &[
            "completion",
            "create",
            "dependency",
            "env",
            "get",
            "history",
            "install",
            "lint",
            "list",
            "package",
            "plugin",
            "pull",
            "push",
            "registry",
            "repo",
            "rollback",
            "search",
            "show",
            "status",
            "template",
            "test",
            "uninstall",
            "upgrade",
            "verify",
            "version",
        ],
    )
}

fn terraform() -> CommandSpec {
    simple(
        "terraform",
        "Infrastructure as code tool",
        &[
            "apply",
            "console",
            "destroy",
            "env",
            "fmt",
            "force-unlock",
            "get",
            "graph",
            "import",
            "init",
            "login",
            "logout",
            "metadata",
            "output",
            "plan",
            "providers",
            "refresh",
            "show",
            "state",
            "taint",
            "test",
            "untaint",
            "validate",
            "version",
            "workspace",
        ],
    )
}

fn podman() -> CommandSpec {
    simple(
        "podman",
        "Daemonless container engine",
        &[
            "attach",
            "build",
            "commit",
            "compose",
            "container",
            "cp",
            "create",
            "diff",
            "events",
            "exec",
            "export",
            "generate",
            "healthcheck",
            "history",
            "image",
            "images",
            "import",
            "info",
            "inspect",
            "kill",
            "load",
            "login",
            "logout",
            "logs",
            "machine",
            "manifest",
            "network",
            "pause",
            "play",
            "pod",
            "port",
            "ps",
            "pull",
            "push",
            "restart",
            "rm",
            "rmi",
            "run",
            "save",
            "search",
            "secret",
            "start",
            "stats",
            "stop",
            "system",
            "tag",
            "top",
            "unpause",
            "unshare",
            "version",
            "volume",
            "wait",
        ],
    )
}

fn python_tool(name: &str, description: &str) -> CommandSpec {
    simple(
        name,
        description,
        &[
            "cache",
            "check",
            "compile",
            "config",
            "download",
            "freeze",
            "hash",
            "help",
            "index",
            "install",
            "list",
            "show",
            "sync",
            "tree",
            "uninstall",
            "wheel",
        ],
    )
}

fn additional_tools() -> Vec<CommandSpec> {
    vec![
        node(
            "aws",
            "Amazon Web Services command-line interface",
            vec![
                leaf("configure", "Configure credentials and defaults"),
                node(
                    "s3",
                    "Manage Amazon S3 objects",
                    leaves(&[
                        "cp", "ls", "mb", "mv", "presign", "rb", "rm", "sync", "website",
                    ]),
                ),
                leaf("s3api", "Access the Amazon S3 API"),
                leaf("cloudformation", "Manage CloudFormation stacks"),
                leaf("dynamodb", "Manage DynamoDB resources"),
                leaf("ec2", "Manage EC2 resources"),
                leaf("ecs", "Manage ECS resources"),
                leaf("eks", "Manage EKS clusters"),
                leaf("iam", "Manage identities and access"),
                leaf("lambda", "Manage Lambda functions"),
                leaf("logs", "Manage CloudWatch Logs"),
                leaf("rds", "Manage relational databases"),
                leaf("secretsmanager", "Manage secrets"),
                leaf("sts", "Manage temporary credentials"),
            ],
        ),
        simple(
            "az",
            "Microsoft Azure command-line interface",
            &[
                "account",
                "acr",
                "ad",
                "aks",
                "appconfig",
                "cloud",
                "config",
                "container",
                "deployment",
                "extension",
                "functionapp",
                "group",
                "keyvault",
                "login",
                "logout",
                "network",
                "rest",
                "role",
                "storage",
                "vm",
                "webapp",
            ],
        ),
        simple(
            "gcloud",
            "Google Cloud command-line interface",
            &[
                "alpha",
                "app",
                "artifacts",
                "auth",
                "beta",
                "builds",
                "components",
                "compute",
                "config",
                "container",
                "dataflow",
                "dataproc",
                "dns",
                "emulators",
                "firestore",
                "functions",
                "iam",
                "info",
                "init",
                "kms",
                "logging",
                "projects",
                "pubsub",
                "run",
                "secrets",
                "services",
                "sql",
                "storage",
                "topic",
                "version",
            ],
        ),
        simple(
            "dotnet",
            ".NET command-line interface",
            &[
                "add", "build", "clean", "format", "help", "list", "msbuild", "new", "nuget",
                "pack", "publish", "remove", "restore", "run", "sln", "store", "test", "tool",
                "workload",
            ],
        ),
        simple(
            "deno",
            "JavaScript and TypeScript runtime",
            &[
                "add",
                "bench",
                "bundle",
                "cache",
                "check",
                "compile",
                "completions",
                "coverage",
                "doc",
                "eval",
                "fmt",
                "info",
                "init",
                "install",
                "jupyter",
                "lint",
                "lsp",
                "outdated",
                "publish",
                "remove",
                "repl",
                "run",
                "serve",
                "task",
                "test",
                "types",
                "uninstall",
                "upgrade",
                "vendor",
            ],
        ),
        simple(
            "poetry",
            "Python dependency and packaging manager",
            &[
                "about", "add", "build", "cache", "check", "config", "debug", "env", "export",
                "help", "init", "install", "list", "lock", "new", "publish", "remove", "run",
                "search", "self", "shell", "show", "source", "update", "version",
            ],
        ),
        simple(
            "conda",
            "Environment and package manager",
            &[
                "activate",
                "clean",
                "commands",
                "compare",
                "config",
                "content-trust",
                "create",
                "deactivate",
                "doctor",
                "env",
                "export",
                "info",
                "init",
                "install",
                "list",
                "notices",
                "package",
                "remove",
                "rename",
                "repoquery",
                "run",
                "search",
                "update",
            ],
        ),
        simple(
            "composer",
            "PHP dependency manager",
            &[
                "about",
                "archive",
                "audit",
                "browse",
                "bump",
                "check-platform-reqs",
                "clear-cache",
                "config",
                "create-project",
                "depends",
                "diagnose",
                "dump-autoload",
                "exec",
                "fund",
                "global",
                "help",
                "init",
                "install",
                "licenses",
                "list",
                "outdated",
                "prohibits",
                "reinstall",
                "remove",
                "require",
                "run-script",
                "search",
                "self-update",
                "show",
                "status",
                "suggests",
                "update",
                "validate",
            ],
        ),
        simple(
            "gradle",
            "Gradle build tool",
            &[
                "assemble",
                "build",
                "buildEnvironment",
                "clean",
                "components",
                "dependencies",
                "dependencyInsight",
                "help",
                "init",
                "javaToolchains",
                "model",
                "outgoingVariants",
                "projects",
                "properties",
                "resolvableConfigurations",
                "tasks",
                "test",
                "wrapper",
            ],
        ),
        simple(
            "mvn",
            "Apache Maven build tool",
            &[
                "clean", "compile", "deploy", "help", "install", "package", "site", "test",
                "validate", "verify",
            ],
        ),
        simple(
            "vagrant",
            "Development environment manager",
            &[
                "box",
                "cloud",
                "destroy",
                "global-status",
                "halt",
                "init",
                "login",
                "package",
                "plugin",
                "port",
                "powershell",
                "provision",
                "push",
                "rdp",
                "reload",
                "resume",
                "snapshot",
                "ssh",
                "ssh-config",
                "status",
                "suspend",
                "up",
                "upload",
                "validate",
                "version",
            ],
        ),
        simple(
            "minikube",
            "Local Kubernetes cluster manager",
            &[
                "addons",
                "cache",
                "completion",
                "config",
                "cp",
                "dashboard",
                "delete",
                "docker-env",
                "image",
                "ip",
                "kubectl",
                "logs",
                "mount",
                "node",
                "pause",
                "podman-env",
                "profile",
                "service",
                "ssh",
                "start",
                "status",
                "stop",
                "tunnel",
                "unpause",
                "update-check",
                "version",
            ],
        ),
        simple(
            "kind",
            "Kubernetes clusters in Docker",
            &[
                "build",
                "completion",
                "create",
                "delete",
                "export",
                "get",
                "load",
                "version",
            ],
        ),
        simple(
            "ansible-galaxy",
            "Manage Ansible roles and collections",
            &["collection", "role"],
        ),
        simple(
            "flyctl",
            "Fly.io command-line interface",
            &[
                "agent",
                "apps",
                "auth",
                "certs",
                "checks",
                "config",
                "dashboard",
                "deploy",
                "destroy",
                "doctor",
                "extensions",
                "image",
                "ips",
                "launch",
                "logs",
                "machine",
                "machines",
                "open",
                "orgs",
                "platform",
                "postgres",
                "proxy",
                "redis",
                "regions",
                "releases",
                "scale",
                "secrets",
                "services",
                "ssh",
                "status",
                "version",
                "volumes",
            ],
        ),
        simple(
            "vercel",
            "Vercel command-line interface",
            &[
                "alias",
                "bisect",
                "build",
                "certs",
                "deploy",
                "dev",
                "dns",
                "domains",
                "env",
                "git",
                "help",
                "init",
                "inspect",
                "integration",
                "link",
                "list",
                "login",
                "logout",
                "logs",
                "project",
                "promote",
                "pull",
                "redeploy",
                "remove",
                "rollback",
                "switch",
                "teams",
                "telemetry",
                "whoami",
            ],
        ),
        simple(
            "netlify",
            "Netlify command-line interface",
            &[
                "addons",
                "api",
                "build",
                "completion",
                "deploy",
                "dev",
                "env",
                "functions",
                "init",
                "integration",
                "link",
                "lm",
                "login",
                "open",
                "recipes",
                "serve",
                "sites",
                "status",
                "switch",
                "unlink",
                "watch",
            ],
        ),
        simple(
            "supabase",
            "Supabase command-line interface",
            &[
                "bootstrap",
                "branches",
                "completion",
                "db",
                "domains",
                "encryption",
                "functions",
                "gen",
                "inspect",
                "link",
                "login",
                "migration",
                "network-bans",
                "network-restrictions",
                "orgs",
                "projects",
                "secrets",
                "services",
                "snippets",
                "ssl-enforcement",
                "start",
                "status",
                "stop",
                "test",
                "unlink",
            ],
        ),
        simple(
            "wrangler",
            "Cloudflare developer command-line interface",
            &[
                "ai",
                "analytics-engine",
                "cert",
                "containers",
                "d1",
                "delete",
                "deploy",
                "dev",
                "dispatch-namespace",
                "docs",
                "hyperdrive",
                "init",
                "kv",
                "login",
                "logout",
                "mtls-certificate",
                "pages",
                "pipelines",
                "pubsub",
                "queues",
                "r2",
                "secret",
                "tail",
                "types",
                "versions",
                "whoami",
                "workflows",
            ],
        ),
        simple(
            "prisma",
            "Prisma database toolkit",
            &[
                "db", "debug", "deploy", "dev", "format", "generate", "init", "migrate",
                "platform", "studio", "validate", "version",
            ],
        ),
        simple(
            "expo",
            "Expo application toolkit",
            &[
                "add",
                "build",
                "config",
                "customize",
                "doctor",
                "eas",
                "export",
                "install",
                "login",
                "logout",
                "prebuild",
                "publish",
                "register",
                "run",
                "send",
                "start",
                "whoami",
            ],
        ),
        simple(
            "adb",
            "Android Debug Bridge",
            &[
                "bugreport",
                "connect",
                "devices",
                "disconnect",
                "emu",
                "forward",
                "install",
                "install-multiple",
                "jdwp",
                "kill-server",
                "logcat",
                "pair",
                "pull",
                "push",
                "reboot",
                "remount",
                "reverse",
                "root",
                "shell",
                "sideload",
                "start-server",
                "sync",
                "tcpip",
                "uninstall",
                "unroot",
                "version",
                "wait-for-device",
            ],
        ),
        option_tool(
            "curl",
            "Transfer data from or to a server",
            &[
                ("--data", "Send request data"),
                ("--fail", "Fail on HTTP errors"),
                ("--form", "Submit multipart form data"),
                ("--head", "Fetch headers only"),
                ("--header", "Add a request header"),
                ("--include", "Include response headers"),
                ("--location", "Follow redirects"),
                ("--output", "Write output to a file"),
                ("--request", "Specify the request method"),
                ("--silent", "Suppress progress output"),
                ("--user", "Set server credentials"),
                ("--verbose", "Show verbose diagnostics"),
            ],
        ),
        option_tool(
            "ssh",
            "OpenSSH remote login client",
            &[
                ("-4", "Use IPv4 only"),
                ("-6", "Use IPv6 only"),
                ("-A", "Forward the authentication agent"),
                ("-i", "Select an identity file"),
                ("-J", "Connect through a jump host"),
                ("-L", "Forward a local port"),
                ("-p", "Select the remote port"),
                ("-R", "Forward a remote port"),
                ("-v", "Enable verbose diagnostics"),
            ],
        ),
        option_tool(
            "rg",
            "Recursively search text",
            &[
                ("--case-sensitive", "Search case-sensitively"),
                ("--files", "Print files that would be searched"),
                ("--fixed-strings", "Treat patterns as literals"),
                ("--glob", "Include or exclude file globs"),
                ("--hidden", "Search hidden files"),
                ("--ignore-case", "Search case-insensitively"),
                ("--type", "Search only a file type"),
            ],
        ),
        option_tool(
            "fd",
            "Find filesystem entries",
            &[
                ("--absolute-path", "Show absolute paths"),
                ("--extension", "Filter by file extension"),
                ("--glob", "Use glob matching"),
                ("--hidden", "Search hidden entries"),
                ("--max-depth", "Set maximum search depth"),
                ("--type", "Filter by entry type"),
            ],
        ),
    ]
}

fn option_tool(name: &str, description: &str, tool_options: &[(&str, &str)]) -> CommandSpec {
    let mut command = leaf(name, description);
    command.options = options(tool_options);
    command
}

fn simple(name: &str, description: &str, subcommands: &[&str]) -> CommandSpec {
    node(name, description, leaves(subcommands))
}

fn leaves(names: &[&str]) -> Vec<CommandSpec> {
    names.iter().map(|name| leaf(name, "")).collect()
}

fn leaf(name: &str, description: &str) -> CommandSpec {
    node(name, description, Vec::new())
}

fn node(name: &str, description: &str, subcommands: Vec<CommandSpec>) -> CommandSpec {
    CommandSpec {
        name: name.into(),
        aliases: Vec::new(),
        description: (!description.is_empty()).then(|| description.into()),
        subcommands,
        options: Vec::new(),
    }
}

fn options(items: &[(&str, &str)]) -> Vec<CommandOption> {
    items
        .iter()
        .map(|(name, description)| CommandOption {
            name: (*name).into(),
            aliases: Vec::new(),
            description: Some((*description).into()),
        })
        .collect()
}
