#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

failure=0
tracked_files=$(git ls-files)

while IFS= read -r path; do
  case "$path" in
    .agents/*|.codex/*|*/.agents/*|*/.codex/*|AGENTS.md|*/AGENTS.md|CLAUDE.md|*/CLAUDE.md|CONTEXT.md|*/CONTEXT.md|ROADMAP.md|*/ROADMAP.md|*_AUDIT.md|*_REVIEW_REPORT.md|.env|.env.*|*/.env|*/.env.*|*.env|*.key|*.pem|*.p12|*.pfx|id_rsa|*/id_rsa|id_ed25519|*/id_ed25519)
      printf 'Forbidden tracked path: %s\n' "$path" >&2
      failure=1
      ;;
  esac
done <<< "$tracked_files"

machine_pattern='(/Users/[^[:space:]]+|/private/var/folders/[^[:space:]]+|[A-Za-z]:\\Users\\[^[:space:]]+)'
if git grep -nI -E "$machine_pattern" -- ':!scripts/repository-hygiene.sh'; then
  printf '%s\n' 'Machine-specific path found in tracked content.' >&2
  failure=1
fi

personal_email_pattern='[A-Za-z0-9._%+-]+@(gmail|icloud|yandex|mail)\.[A-Za-z]{2,}'
if git grep -nI -E "$personal_email_pattern" -- ':!scripts/repository-hygiene.sh'; then
  printf '%s\n' 'Personal email address found in tracked content.' >&2
  failure=1
fi

ai_pattern='(Chat''GPT|Open''AI|Anthropic|Codex agent|Claude agent|generated by (an )?AI|LLM-generated)'
if git grep -nI -E "$ai_pattern" -- ':!scripts/repository-hygiene.sh'; then
  printf '%s\n' 'Internal AI-authorship or agent content found in tracked files.' >&2
  failure=1
fi

private_key_pattern='BEGIN (RSA |OPENSSH |EC |DSA )?PRIVATE KEY'
if git grep -nI -E "$private_key_pattern" -- ':!scripts/repository-hygiene.sh'; then
  printf '%s\n' 'Private key material found in tracked content.' >&2
  failure=1
fi

if ((failure)); then
  exit 1
fi

printf '%s\n' 'REPOSITORY-HYGIENE:tracked-content:ok'
