pub mod actions;
pub mod app;
pub mod cli;
pub mod config;
pub mod config_edit;
pub mod error;
pub mod fixture;
pub mod history_import;
pub mod index;
pub mod model;
pub mod palette;
pub mod paths;
pub mod roots;
pub mod search;
pub mod setup;
pub mod shell;
pub mod state;
pub mod suggestions;
pub mod terminal;
pub mod tui;
pub mod update;

pub use error::{DirgoError, Result};
